//
// Base config
//
// @link http://eslint.org/docs/rules
// @link http://eslint.org/docs/user-guide/configuring
//
// 0 - off
// 1 - warning
// 2 - error
//

'use strict';

module.exports = {

	env : {
		node     : true,
		commonjs : true,
		es6      : false,
	},

	parserOptions : {
		ecmaVersion : 5,
	},

	rules : {

		// Possible errors
		// 'comma-dangle'                      : [ 0, 'always-multiline' ],
		'no-cond-assign'                    : 2,
		// 'no-console'                        : 0,
		'no-constant-condition'             : 2,
		'no-control-regex'                  : 2,
		'no-debugger'                       : 2,
		'no-dupe-keys'                      : 2,
		'no-dupe-args'                      : 2,
		'no-duplicate-case'                 : 2,
		'no-empty-character-class'          : 2,
		'no-empty'                          : 1,
		'no-ex-assign'                      : 2,
		'no-extra-boolean-cast'             : 2,

		// Disabled due to conflict with `no-confusing-arrow`: https://github.com/eslint/eslint/issues/6196
		// 'no-extra-parens'                   : [ 2, 'all', { conditionalAssign : false, returnAssign : false, nestedBinaryExpressions : false } ],

		'no-extra-semi'                     : 2,
		'no-func-assign'                    : 2,
		'no-inner-declarations'             : [ 2, 'functions' ],
		'no-invalid-regexp'                 : 2,
		'no-irregular-whitespace'           : 2,
		'no-negated-in-lhs'                 : 2,
		'no-obj-calls'                      : 2,
		'no-prototype-builtins'             : 2,
		'no-regex-spaces'                   : 2,
		// 'no-restricted-globals'             : 0,
		'no-sparse-arrays'                  : 2,
		'no-unreachable'                    : 2,
		'no-unsafe-finally'                 : 2,
		'use-isnan'                         : 2,
		// 'valid-jsdoc'                       : 0,
		'valid-typeof'                      : 2,
		'no-unexpected-multiline'           : 2,


		// Best practices
		'accessor-pairs'                    : 1,
		'array-callback-return'             : 2,
		// 'block-scoped-var'                  : 0,
		// 'complexity'                        : [ 0, 11 ],
		'consistent-return'                 : 2,
		'curly'                             : [ 2, 'all' ],
		// 'default-case'                      : 0,
		'dot-notation'                      : [ 2, { 'allowKeywords' : true } ],
		// 'dot-location'                      : 0,
		'eqeqeq'                            : 2,
		// 'guard-for-in'                      : 0,
		'no-alert'                          : 1,
		'no-caller'                         : 2,
		'no-case-declarations'              : 2,
		// 'no-div-regex'                      : 0,
		'no-else-return'                    : 1,
		'no-empty-function'                 : 1,
		'no-empty-pattern'                  : 2,
		'no-eq-null'                        : 1,
		'no-eval'                           : 2,
		'no-extend-native'                  : 2,
		'no-extra-bind'                     : 2,
		'no-extra-label'                    : 1,
		'no-fallthrough'                    : 1,
		'no-floating-decimal'               : 1,
		// 'no-implicit-coercion'              : 0,
		'no-implicit-globals'               : 1,
		'no-implied-eval'                   : 2,
		'no-invalid-this'                   : 1,
		'no-iterator'                       : 2,
		'no-labels'                         : 2,
		'no-lone-blocks'                    : 2,
		'no-loop-func'                      : 2,
		// 'no-magic-numbers'                  : 0,
		// 'no-multi-spaces'                   : 0,
		'no-multi-str'                      : 2,
		'no-native-reassign'                : 2,
		'no-new-func'                       : 2,
		'no-new-wrappers'                   : 1,
		'no-new'                            : 1,
		'no-octal-escape'                   : 2,
		'no-octal'                          : 2,
		'no-param-reassign'                 : [ 2, { 'props' : true } ],
		// 'no-process-env'                    : 0,
		'no-proto'                          : 2,
		'no-redeclare'                      : 2,
		'no-return-assign'                  : 1,
		'no-script-url'                     : 2,
		'no-self-assign'                    : 2,
		'no-self-compare'                   : 1,
		'no-sequences'                      : 2,
		'no-throw-literal'                  : 1,
		// 'no-unmodified-loop-condition'      : 0,
		'no-unused-expressions'             : 1,
		'no-unused-labels'                  : 1,
		'no-useless-call'                   : 1,
		'no-useless-concat'                 : 1,
		'no-useless-escape'                 : 2,
		// 'no-void'                           : 0,
		// 'no-warning-comments'               : [ 0, { 'terms' : [ 'todo', 'fixme', 'xxx' ], 'location' : 'start' } ],
		'no-with'                           : 2,
		// 'radix'                             : 0,
		// 'vars-on-top'                       : 0,
		'wrap-iife'                         : [ 1, 'outside' ],
		'yoda'                              : [ 2, 'never' ],


		// Strict mode
		'strict'                            : [ 2, 'safe' ],


		// Variables
		// 'init-declarations'                 : 0,
		// 'no-catch-shadow'                   : 0,
		'no-delete-var'                     : 2,
		'no-label-var'                      : 2,
		'no-shadow-restricted-names'        : 2,
		'no-shadow'                         : 2,
		'no-undef-init'                     : 2,
		'no-undef'                          : 2,
		'no-undefined'                      : 1,
		// 'no-unused-vars'                    : [ 0, { 'vars' : 'all', 'args' : 'none' } ],
		'no-use-before-define'              : [ 1, 'nofunc' ],


		// Node.js & CommonJS
		'callback-return'                   : [2, [ 'callback', 'cb', 'next', 'done' ] ],
		'global-require'                    : 1,
		// 'handle-callback-err'               : 0,
		// 'no-mixed-requires'                 : [ 0, true ],
		'no-new-require'                    : 1,
		'no-path-concat'                    : 1,
		'no-process-exit'                   : 2,
		// 'no-restricted-imports'             : 0,
		// 'no-restricted-modules'             : 0,
		// 'no-sync'                           : 0,


		// Stylistic issues
		// 'array-bracket-spacing'             : [ 0, 'always' ],
		'block-spacing'                     : [ 1, 'always' ],
		// 'brace-style'                       : [ 0, '1tbs', { 'allowSingleLine' : true } ],
		'camelcase'                         : 1,
		// 'comma-spacing'                     : 0,
		// 'comma-style'                       : [ 0, 'last' ],
		// 'computed-property-spacing'         : 0,
		// 'consistent-this'                   : [ 0, 'self' ],
		// 'eol-last'                          : 0,
		// 'func-names'                        : 0,
		// 'func-style'                        : [ 0, 'declaration' ],
		// 'id-blacklist'                      : 0,
		// 'id-length'                         : 0,
		// 'id-match'                          : 0,
		'indent'                            : [ 1, 'tab', { 'SwitchCase' : 1, 'VariableDeclarator' : 1 } ],
		// 'key-spacing'                       : [ 0, { 'beforeColon' : true, 'afterColon' : true, 'mode' : 'minimum' } ],
		// 'keyword-spacing'                   : 0,
		'linebreak-style'                   : [ 1, 'unix' ],
		// 'lines-around-comment'              : 0,
		// 'max-depth'                         : [ 0, 4 ],
		// 'max-len'                           : [ 0, 80, 4 ],
		// 'max-lines'                         : 0,
		// 'max-nested-callbacks'              : [ 0, 2 ],
		// 'max-params'                        : [ 0, 3 ],
		// 'max-statements'                    : [ 0, 10 ],
		// 'max-statements-per-line'           : [ 0, { max: 1 } ],
		// 'new-cap'                           : 0,
		// 'new-parens'                        : 0,
		// 'newline-after-var'                 : 0,
		// 'newline-before-return'             : 0,
		// 'newline-per-chained-call'          : 0,
		'no-array-constructor'              : 1,
		// 'no-continue'                       : 0,
		// 'no-inline-comments'                : 0,
		// 'no-lonely-if'                      : 0,
		'no-mixed-operators'                : 1,
		'no-mixed-spaces-and-tabs'          : [ 2, 'smart-tabs' ],
		// 'no-multiple-empty-lines'           : [ 0, { 'max' : 2 } ],
		'no-negated-condition'              : 1,
		// 'no-nested-ternary'                 : 0,
		'no-new-object'                     : 2,
		// 'no-restricted-syntax'              : 0,
		// 'no-spaced-func'                    : 0,
		// 'no-ternary'                        : 0,
		'no-trailing-spaces'                : 1,
		// 'no-underscore-dangle'              : 0,
		'no-unneeded-ternary'               : 1,
		'no-whitespace-before-property'     : 1,
		// 'object-curly-newline'              : 0,
		// 'object-curly-spacing'              : 0,
		// 'object-property-newline'           : 0,
		// 'one-var'                           : [ 0, 'never' ],
		// 'one-var-declaration-per-line'      : 0,
		// 'operator-assignment'               : [ 0, 'always' ],
		// 'operator-linebreak'                : [ 0, 'after' ],
		// 'padded-blocks'                     : [ 0, 'always' ],
		'quote-props'                       : [ 2, 'as-needed', { keywords : false } ],
		'quotes'                            : [ 2, 'single', { avoidEscape : true, allowTemplateLiterals : false } ],
		// 'require-jsdoc'                     : 0,
		'semi'                              : [ 2, 'always' ],
		// 'semi-spacing'                      : [ 0, { 'before' : false, 'after' : true } ],
		// 'sort-imports'                      : 0,
		// 'sort-vars'                         : 0,
		// 'space-before-blocks'               : [ 0, 'always' ],
		// 'space-before-function-paren'       : [ 0, { 'anonymous' : 'never', 'named' : 'always' } ],
		// 'space-in-brackets'                 : [ 0, 'always' ],
		// 'space-in-parens'                   : [ 0, 'always', { 'exceptions' : [ 'empty' ] } ],
		// 'space-infix-ops'                   : 0,
		// 'space-unary-ops'                   : [ 0, { 'words' : true, 'nonwords' : false } ],
		// 'spaced-comment'                    : [ 0, 'always' ],
		'unicode-bom'                       : [ 2, 'never' ],
		// 'wrap-regex'                        : 0,


		// Legacy
		// 'no-bitwise'                        : 0,
		// 'no-plusplus'                       : 0,

	},

};
